### ISSUE TITLE
No JSON object could be decoded

### ISSUE THREAD

**Issue by BoogalooXiang** [thu-media/QARC#8]
I followed readme file and ran trans.py, main.py , process-vmaf.py one by one. I used vmaf-1.3.9 but the error come out: No JSON object could be decoded. And my json file is empty. Has anyone met with this problem? Can anybody tell me how to solve that? thx :D

**Comment by kasimte** [comment]
I think I've seen this. Can you post a log?

**Comment by BoogalooXiang** [comment]
Traceback (most recent call last):

  File "../ffmpeg2vmaf", line 8, in <module>
    from vmaf.config import VmafConfig, DisplayConfig
ImportError: No module named vmaf.config

Traceback (most recent call last):

  File "generate.py", line 62, in <module>
    eventloop(_file)
  File "generate.py", line 44, in eventloop
    data = json.load(json_file)
  File "/usr/lib/python2.7/json/__init__.py", line 291, in load
    **kw)
  File "/usr/lib/python2.7/json/__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python2.7/json/decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python2.7/json/decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

**Comment by kasimte** [comment]
It looks like it is trying to read a json file on this line:

https://github.com/thu-media/QARC/blob/02c081703e5fd8fd0787b308aed3a48283d1ad7f/videodatasets/generate.py#L42

Did you print the filename and check if the json file exists?

**Comment by BoogalooXiang** [comment]
Yeah the json file do exist but I found it was an empty file when I opened it. 
I used
 ` print json_file` 
before
 `data = json.load(json_file)`
and it showed:
<open file 'tmp_0.flv.json', mode 'r' at 0x7f002321f390>

**Comment by kasimte** [comment]
That looks like the culprit. If you get the training data processing to work, I would be grateful if you would let me know. I tried following the README instructions and ended up with files with a lot of `NaN`s that couldn't be used for training.
